name: Pull Request CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: |
        uv pip install --system -e .[dev]
    
    - name: Format check with Black
      run: |
        black --check --diff .
    
    - name: Lint with Ruff
      run: |
        ruff check .
    
    - name: Type check with mypy
      run: |
        mypy l0
    
    - name: Run tests with coverage
      run: |
        pytest tests/ -v --cov=l0 --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Build package
      run: python -m build