name: Push to Main CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: |
        uv pip install --system -e .[dev]
    
    - name: Format check with Black
      run: |
        black --check --diff .
    
    - name: Type check with mypy
      run: |
        mypy l0
    
    - name: Run tests with coverage
      run: |
        pytest tests/ -v --cov=l0 --cov-report=xml --cov-report=term-missing
    
    # Codecov upload commented out - requires token setup
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v4
    #   with:
    #     file: ./coverage.xml
    #     fail_ci_if_error: false
    #     token: ${{ secrets.CODECOV_TOKEN }}

    - name: Build package
      run: python -m build
    
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI }}
        skip-existing: true

  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    
    - name: Install documentation dependencies
      run: |
        pip install -e .[docs]
    
    - name: Build documentation
      run: |
        jupyter-book build docs
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html